
sudo: false

language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt

script: 
  - pelican

after_success:
  - export COMMIT_MSG=$(git log -1 --oneline --format="%s")
  - cd public
  - git add .
  - git commit --allow-empty -m "$(COMMIT_MSG)"
  - git push origin HEAD:gh-pages

branches:
  only:
    - master