
sudo: false

language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt

script: 
  - pelican

after_success:
  - export COMMIT_MSG=$(git log -1 --oneline --format="%s")
  - cd public
  - git config --global user.email "Yoker.Wu@gmail.com"
  - git config --global user.name "Yoker.Wu"
  - git add .
  - git commit -m "$COMMIT_MSG"
  - git push origin HEAD:gh-pages

branches:
  only:
    - master